server:
  port: ${gateway.port:8080}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: http://${order.ip:127.0.0.1}:${order.port:8081}/
          predicates:
            - Path=/orders/**
        - id: PaymentService
          uri: http://${payment.ip:127.0.0.1}:${payment.port:8082}/
          predicates:
            - Path=/pay/**
        - id: CarService
          uri: http://${car.ip:127.0.0.1}:${car.port:8083}/
          predicates:
            - Path=/cars/**
        - id: UserService
          uri: http://${user.ip:127.0.0.1}:${user.port:8084}/
          predicates:
            - Path=/users/**
        - id: AccountingService
          uri: http://${accounting.ip:127.0.0.1}:${accounting.port:8085}/
          predicates:
            - Path=/bills/**
            - Path=/balance/**
