server:
  address: ${GATEWAY_ADDRESS:localhost}
  port: ${GATEWAY_PORT:8080}

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: http://${ORDER_ADDRESS:127.0.0.1}:${ORDER_PORT:8081}/
          predicates:
            - Path=/orders/**
        - id: PaymentService
          uri: http://${PAYMENT_ADDRESS:127.0.0.1}:${PAYMENT_PORT:8082}/
          predicates:
            - Path=/pay/**
        - id: CarService
          uri: http://${CAR_ADDRESS:127.0.0.1}:${CAR_PORT:8083}/
          predicates:
            - Path=/cars/**
        - id: UserService
          uri: http://${USER_ADDRESS:127.0.0.1}:${USER_PORT:8084}/
          predicates:
            - Path=/users/**
        - id: AccountingService
          uri: http://${ACCOUNTING_ADDRESS:127.0.0.1}:${ACCOUNTING_PORT:8085}/
          predicates:
            - Path=/bills/**
            - Path=/balance/**
