server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/orders/**
        - id: PaymentService
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/pay/**
        - id: CarService
          uri: http://127.0.0.1:8083/
          predicates:
            - Path=/cars/**
        - id: UserService
          uri: http://127.0.0.1:8084/
          predicates:
            - Path=/users/**
        - id: AccountingService
          uri: http://127.0.0.1:8085/
          predicates:
            - Path=/bills/**
            - Path=/balance/**
